/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_core_ext_ExtFacade */

#ifndef _Included_com_core_ext_ExtFacade
#define _Included_com_core_ext_ExtFacade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_core_ext_ExtFacade
 * Method:    execute
 * Signature: (Lcom/core/ext/ExtFacade/Data;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_core_ext_ExtFacade_execute
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_ext_ExtFacade
 * Method:    getData
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_core_ext_ExtFacade_getData
  (JNIEnv *, jobject);

/*
 * Class:     com_core_ext_ExtFacade
 * Method:    writeSerial
 * Signature: (Lcom/core/ext/ExtFacade/Com;)V
 */
JNIEXPORT void JNICALL Java_com_core_ext_ExtFacade_writeSerial
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_ext_ExtFacade
 * Method:    readSerial
 * Signature: (Lcom/core/ext/ExtFacade/Com;)V
 */
JNIEXPORT void JNICALL Java_com_core_ext_ExtFacade_readSerial
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
